
version: 2

models:
  - name: stg_sales
    description: "Staging view for sales transaction."
    columns:
      - name: sales_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
